name: 'Markdown Reviwer and Translator'
description: 'Markdown grammar reviewer and translation into any other language powered by Google Gemini'
author: 'Thiago Mendonca'
branding:
  icon: 'book-open'
  color: 'purple'
inputs:
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    default: ${{ github.token }}
  aiApiKey:
    description: API Key to use the AI service
    required: true
  aiProvider:
    description: 'AI Provider'
    required: false
    default: 'google'
  aiModel:
    description: 'AI language model to use.'
    required: false
    default: 'gemini-1.5-flash'
  translateCommitMessageTemplate:
    description: 'Commit message template when creating new translated file. %file is replaced with the file name and %lang with language'
    required: false
    default: 'add translation of file %file for language %lang'
  applyReviewCommitMessageTemplate:
    description: 'Commit message template when creating a reviewed file. %file is replaced with the file name'
    required: false
    default: 'apply review suggestions for file %file'
runs:
  using: 'node20'
  main: 'dist/index.js'
